version: '3.8'

volumes:
  pgdata:

services:

  postgres:
    container_name: itmo_postgres
    image: postgis/postgis:latest
    env_file:
      - ./docker/env/prod/.env.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
        - "2345:5432"

  web:
    container_name: itmo_web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - ./docker/env/prod/.env.web
    volumes:
      - ./:/app
    depends_on:
      - postgres
    command: sh -c "./src/v1/alembic upgrade head && python -m src.v1.capital_cities.main"

  nginx:
    container_name: itmo_nginx
    working_dir: /app
    image: nginx:stable-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/dev/:/etc/nginx/conf.d:ro
    links:
      - web
    depends_on:
      - web
